### PR TITLE
Fix to drush migration purge to prevent deleting all users.

### PR DESCRIPTION
**Pull request by davidrkupton**
#### Fixes [insert bug/issue number]
#1050 

#### Changes proposed in this pull request:
* Adds some checking to be sure data exists in migrate import
* Changes strategy to disable purged users rather than delete by default.
* Adds drush flag to force deletion of purged users.

#### Add @mentions of the person or team responsible for reviewing proposed changes
@jimafisk

### CODE REVIEW

**Comment by davidrkupton** [comment]
@jimafisk : I cannot get the import to work locally.
I have made a lot of smaller changes to import and process logic which are simple and should work, but do need to be tested.  Any suggestions on how I can do this testing?
Thanks.

**Comment by jimafisk** [comment]
This might be because `hub-migrate-purge` is a custom drush command that I added and probably can't accommodate the `--dry-run` flag.

**Comment by jimafisk** [comment]
nm, looking back at this, there is a `--dry-run` option. Let me try this locally.

**Comment by jimafisk** [comment]
I was getting the same `Bad JSON data retrieved from source.` error:

new_migration_purge

It seemed like the `drupal_json_decode()` was choking so I ran the JSON through a validator and found 2 instances of unicode arrow characters. Stripping those out of the JSON we fetch seems to clear this up:

migrate

**Pull request merged**
